version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:80"
    env_file:
      - ./eVar/.env
    depends_on:
      - score_db
    networks:
      - app_network
    environment:
      - DB_HOST=score_db
      - DOCKER_CONTAINER=true

  score_db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: planning_db
      MYSQL_USER: score
      MYSQL_PASSWORD: Un1sd4
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  static_volume: