# Generated by Django 5.0.6 on 2024-11-20 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StrategicTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('theme_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='strategic_planning.kpi')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_score', models.CharField(choices=[('100', '100'), ('50-99', '50-99'), ('1-49', '1-49'), ('0', '0')], max_length=10)),
                ('color_code', models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=10)),
                ('explanation', models.TextField()),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='strategic_planning.activity')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('objective_name', models.CharField(max_length=200)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='strategic_planning.designation')),
                ('strategic_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='strategic_planning.strategictheme')),
            ],
        ),
        migrations.AddField(
            model_name='kpi',
            name='strategic_objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='strategic_planning.strategicobjective'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('physical_address', models.TextField()),
                ('last_logged_in', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='strategic_planning.designation')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='strategic_planning.role')),
            ],
        ),
        migrations.AddField(
            model_name='strategictheme',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategic_planning.user'),
        ),
        migrations.AddField(
            model_name='strategicobjective',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategic_planning.user'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=10)),
                ('report_details', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='strategic_planning.activity')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategic_planning.designation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategic_planning.user')),
            ],
        ),
        migrations.AddField(
            model_name='kpi',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategic_planning.user'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategic_planning.user'),
        ),
    ]
