# Generated by Django 5.0.6 on 2024-11-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_planning', '0002_auto_20241125_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='actual_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='report',
            name='goal_score',
            field=models.CharField(choices=[('Completed', 'green'), ('Progressing', 'orange'), ('Early Stage', 'yellow'), ('No Activity', 'red')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(null=True),
        ),
    ]
