# Generated by Django 5.0.6 on 2024-11-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_planning', '0003_alter_report_actual_spent_alter_report_goal_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='goal_score',
            field=models.CharField(choices=[('green', 'Completed'), ('orange', 'Progressing'), ('yellow', 'Early Stage'), ('red', 'No Activity')], max_length=20),
        ),
    ]
