# Generated by Django 5.0.6 on 2024-12-01 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_planning', '0005_remove_report_status_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Activities', to='strategic_planning.designation'),
        ),
    ]
