# Generated by Django 5.1.3 on 2024-11-24 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_planning', '0005_activity_end_date_activity_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainactivity',
            name='kpi',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_activities', to='strategic_planning.kpi'),
        ),
    ]
